<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="$(MSBuildThisFileDirectory)../../../../../build/BaseProject.props"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
    </PropertyGroup>

    <!-- Implicit Usings -->
    <ItemGroup>
        <Using Include="Loretta.Utilities"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Tsu" Version="2.2.2"/>
        <PackageReference Include="TUnit" Version="0.19.32"/>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Portable\Loretta.CodeAnalysis.csproj"/>
        <ProjectReference Include="..\..\..\Core\Test\Utilities\Loretta.CodeAnalysis.Test.Utilities.csproj"/>
        <ProjectReference Include="..\..\..\Lua\Portable\Loretta.CodeAnalysis.Lua.csproj"/>
        <ProjectReference Include="..\..\Experimental\Loretta.CodeAnalysis.Lua.Experimental.csproj"/>
        <ProjectReference Include="..\Utilities\Loretta.CodeAnalysis.Lua.Test.Utilities.csproj"/>
    </ItemGroup>

</Project>
