name: Loretta Feature Request
description: A request for a non-language specific feature
type: Feature
labels: ["enhancement"]
body:
  # HEADER
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to submit this request.

        **Important:**
        - Be respectful in your communication. Any disrespect will result in a ban from the repository.
        - Ensure that you have checked the latest Loretta version (including nigthlies) for this feature.
        - Do not leave any field blank. Please fill all of them in or your issue will be closed.
  # Description
  - type: textarea
    id: description
    attributes:
      label: What feature are you requesting?
      description: A clear and concise description of what the feature is.
      placeholder: I'd like to have feature X which allows you to Y.
    validations:
      required: True
  # Extra Info
  - type: textarea
    id: extra-info
    attributes:
      label: Can you go in further detail of what this feature is about?
      description: A more in-depth description of the feature, providing use cases, test cases, documentation links and other useful information.
    validations:
      required: True
  # Preventive Steps
  - type: checkboxes
    id: sanity-checks
    attributes:
      label: "Please ensure you have done the following actions:"
      options:
        - label: I have checked that there are no similar requests already open.
          required: True
        - label: I have confirmed that this has not been implemented on the latest nightly version.
          required: True
        - label: I have confirmed that this feature will be useful for all (or most) users of Loretta.
          required: True
        - label: I acknowledge my issue will be closed if any step has been skipped.
          required: True
    validations:
      required: True