// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific
// target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Lexing.GLuaLexer.TryReadToken(GParse.Lexing.Token@)~System.Boolean" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0014:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Parsing.GLuaParser.ParseSuffixedExpression(Loretta.Parsing.Nodes.ASTNode,Loretta.Parsing.Scope)~Loretta.Parsing.Nodes.ASTNode" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Parsing.GLuaParser.ParseLiteralExpression(Loretta.Parsing.Nodes.ASTNode,Loretta.Parsing.Scope)~Loretta.Parsing.Nodes.ASTNode" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Parsing.GLuaParser.ParseForStatement(Loretta.Parsing.Nodes.ASTNode,Loretta.Parsing.Scope)~Loretta.Parsing.Nodes.ASTNode" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Parsing.GLuaParser.ParseStatementInternal(Loretta.Parsing.Nodes.ASTNode,Loretta.Parsing.Scope)~Loretta.Parsing.Nodes.ASTNode" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0014:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Folder.ConstantASTFolder.FoldBinaryOperatorExpression(Loretta.Parsing.Nodes.Operators.BinaryOperatorExpression,System.Object[])~Loretta.Parsing.Nodes.ASTNode" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Folder.ConstantASTFolder.FoldUnaryOperatorExpression(Loretta.Parsing.Nodes.Operators.UnaryOperatorExpression,System.Object[])~Loretta.Parsing.Nodes.ASTNode" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0013:Use ternary operator", Justification = "R E A D A B I L I T Y", Scope = "member", Target = "~M:Loretta.Folder.BaseASTFolder.FoldBinaryOperatorExpression(Loretta.Parsing.Nodes.Operators.BinaryOperatorExpression,System.Object[])~Loretta.Parsing.Nodes.ASTNode" )]
