//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loretta.CodeAnalysis.Lua {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loretta.CodeAnalysis.Lua.LuaResources", typeof(LuaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax ambiguous between a function call and a new statement.
        /// </summary>
        internal static string ERR_AmbiguousFunctionCallOrNewStatement {
            get {
                return ResourceManager.GetString("ERR_AmbiguousFunctionCallOrNewStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad character input: &apos;{0}&apos;.
        /// </summary>
        internal static string ERR_BadCharacter {
            get {
                return ResourceManager.GetString("ERR_BadCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary numeric literals are not supported in this lua version.
        /// </summary>
        internal static string ERR_BinaryNumericLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_BinaryNumericLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This expression cannot be assigned to.
        /// </summary>
        internal static string ERR_CannotBeAssignedTo {
            get {
                return ResourceManager.GetString("ERR_CannotBeAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C comments are not supported in this lua version.
        /// </summary>
        internal static string ERR_CCommentsNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_CCommentsNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal floating point numeric literals are not supported in this lua version.
        /// </summary>
        internal static string ERR_HexFloatLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_HexFloatLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal string escapes are not supported in this lua version.
        /// </summary>
        internal static string ERR_HexStringEscapesNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_HexStringEscapesNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number.
        /// </summary>
        internal static string ERR_InvalidNumber {
            get {
                return ResourceManager.GetString("ERR_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string escape.
        /// </summary>
        internal static string ERR_InvalidStringEscape {
            get {
                return ResourceManager.GetString("ERR_InvalidStringEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters with value above 0x7F are not supported in this lua version.
        /// </summary>
        internal static string ERR_LuajitIdentifierRulesNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_LuajitIdentifierRulesNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function calls are the only expressions that can be used as statements.
        /// </summary>
        internal static string ERR_NonFunctionCallBeingUsedAsStatement {
            get {
                return ResourceManager.GetString("ERR_NonFunctionCallBeingUsedAsStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric literal is too large.
        /// </summary>
        internal static string ERR_NumericLiteralTooLarge {
            get {
                return ResourceManager.GetString("ERR_NumericLiteralTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal numeric literals are not supported in this lua version.
        /// </summary>
        internal static string ERR_OctalNumericLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_OctalNumericLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shebangs are not supported in this lua version.
        /// </summary>
        internal static string ERR_ShebangNotSupportedInLuaVersion {
            get {
                return ResourceManager.GetString("ERR_ShebangNotSupportedInLuaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underscores in numeric literals are not supported in this lua version.
        /// </summary>
        internal static string ERR_UnderscoreInNumericLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_UnderscoreInNumericLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unescaped line break in string.
        /// </summary>
        internal static string ERR_UnescapedLineBreakInString {
            get {
                return ResourceManager.GetString("ERR_UnescapedLineBreakInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token {0}, expected {1}.
        /// </summary>
        internal static string ERR_UnexpectedToken {
            get {
                return ResourceManager.GetString("ERR_UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished long comment.
        /// </summary>
        internal static string ERR_UnfinishedLongComment {
            get {
                return ResourceManager.GetString("ERR_UnfinishedLongComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished string.
        /// </summary>
        internal static string ERR_UnfinishedString {
            get {
                return ResourceManager.GetString("ERR_UnfinishedString", resourceCulture);
            }
        }
    }
}
