//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loretta.CodeAnalysis.Lua {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuaResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuaResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Loretta.CodeAnalysis.Lua.LuaResources", typeof(LuaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ERR_AmbiguousFunctionCallOrNewStatement {
            get {
                return ResourceManager.GetString("ERR_AmbiguousFunctionCallOrNewStatement", resourceCulture);
            }
        }
        
        internal static string ERR_BadCharacter {
            get {
                return ResourceManager.GetString("ERR_BadCharacter", resourceCulture);
            }
        }
        
        internal static string ERR_BadDocumentationMode {
            get {
                return ResourceManager.GetString("ERR_BadDocumentationMode", resourceCulture);
            }
        }
        
        internal static string ERR_BinaryNumericLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_BinaryNumericLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_BitwiseOperatorsNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_BitwiseOperatorsNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_CannotBeAssignedTo {
            get {
                return ResourceManager.GetString("ERR_CannotBeAssignedTo", resourceCulture);
            }
        }
        
        internal static string ERR_CCommentsNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_CCommentsNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_CloseParenExpected {
            get {
                return ResourceManager.GetString("ERR_CloseParenExpected", resourceCulture);
            }
        }
        
        internal static string ERR_CompoundAssignmentNotSupportedInLuaVersion {
            get {
                return ResourceManager.GetString("ERR_CompoundAssignmentNotSupportedInLuaVersion", resourceCulture);
            }
        }
        
        internal static string ERR_DoubleOverflow {
            get {
                return ResourceManager.GetString("ERR_DoubleOverflow", resourceCulture);
            }
        }
        
        internal static string ERR_EscapeTooLarge {
            get {
                return ResourceManager.GetString("ERR_EscapeTooLarge", resourceCulture);
            }
        }
        
        internal static string ERR_ExpressionExpected {
            get {
                return ResourceManager.GetString("ERR_ExpressionExpected", resourceCulture);
            }
        }
        
        internal static string ERR_HexDigitExpected {
            get {
                return ResourceManager.GetString("ERR_HexDigitExpected", resourceCulture);
            }
        }
        
        internal static string ERR_HexFloatLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_HexFloatLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_HexStringEscapesNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_HexStringEscapesNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_IdentifierExpected {
            get {
                return ResourceManager.GetString("ERR_IdentifierExpected", resourceCulture);
            }
        }
        
        internal static string ERR_IdentifierExpectedKW {
            get {
                return ResourceManager.GetString("ERR_IdentifierExpectedKW", resourceCulture);
            }
        }
        
        internal static string ERR_IfExpressionConditionExpected {
            get {
                return ResourceManager.GetString("ERR_IfExpressionConditionExpected", resourceCulture);
            }
        }
        
        internal static string ERR_IfExpressionConditionExpected_Description {
            get {
                return ResourceManager.GetString("ERR_IfExpressionConditionExpected_Description", resourceCulture);
            }
        }
        
        internal static string ERR_IfExpressionConditionExpected_Title {
            get {
                return ResourceManager.GetString("ERR_IfExpressionConditionExpected_Title", resourceCulture);
            }
        }
        
        internal static string ERR_IfExpressionsNotSupportedInLuaVersion {
            get {
                return ResourceManager.GetString("ERR_IfExpressionsNotSupportedInLuaVersion", resourceCulture);
            }
        }
        
        internal static string ERR_InsufficientStack {
            get {
                return ResourceManager.GetString("ERR_InsufficientStack", resourceCulture);
            }
        }
        
        internal static string ERR_InvalidExpressionPart {
            get {
                return ResourceManager.GetString("ERR_InvalidExpressionPart", resourceCulture);
            }
        }
        
        internal static string ERR_InvalidNumber {
            get {
                return ResourceManager.GetString("ERR_InvalidNumber", resourceCulture);
            }
        }
        
        internal static string ERR_InvalidStatement {
            get {
                return ResourceManager.GetString("ERR_InvalidStatement", resourceCulture);
            }
        }
        
        internal static string ERR_InvalidStringEscape {
            get {
                return ResourceManager.GetString("ERR_InvalidStringEscape", resourceCulture);
            }
        }
        
        internal static string ERR_LbraceExpected {
            get {
                return ResourceManager.GetString("ERR_LbraceExpected", resourceCulture);
            }
        }
        
        internal static string ERR_Lua51NestingInLongString {
            get {
                return ResourceManager.GetString("ERR_Lua51NestingInLongString", resourceCulture);
            }
        }
        
        internal static string ERR_LuajitIdentifierRulesNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_LuajitIdentifierRulesNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_LuajitSuffixInFloat {
            get {
                return ResourceManager.GetString("ERR_LuajitSuffixInFloat", resourceCulture);
            }
        }
        
        internal static string ERR_MixingNilableAndIntersectionNotAllowed {
            get {
                return ResourceManager.GetString("ERR_MixingNilableAndIntersectionNotAllowed", resourceCulture);
            }
        }
        
        internal static string ERR_MixingNilableAndIntersectionNotAllowed_Description {
            get {
                return ResourceManager.GetString("ERR_MixingNilableAndIntersectionNotAllowed_Description", resourceCulture);
            }
        }
        
        internal static string ERR_MixingNilableAndIntersectionNotAllowed_Title {
            get {
                return ResourceManager.GetString("ERR_MixingNilableAndIntersectionNotAllowed_Title", resourceCulture);
            }
        }
        
        internal static string ERR_MixingUnionsAndIntersectionsNotAllowed {
            get {
                return ResourceManager.GetString("ERR_MixingUnionsAndIntersectionsNotAllowed", resourceCulture);
            }
        }
        
        internal static string ERR_MixingUnionsAndIntersectionsNotAllowed_Description {
            get {
                return ResourceManager.GetString("ERR_MixingUnionsAndIntersectionsNotAllowed_Description", resourceCulture);
            }
        }
        
        internal static string ERR_MixingUnionsAndIntersectionsNotAllowed_Title {
            get {
                return ResourceManager.GetString("ERR_MixingUnionsAndIntersectionsNotAllowed_Title", resourceCulture);
            }
        }
        
        internal static string ERR_NonFunctionCallBeingUsedAsStatement {
            get {
                return ResourceManager.GetString("ERR_NonFunctionCallBeingUsedAsStatement", resourceCulture);
            }
        }
        
        internal static string ERR_NormalTypeParametersComeBeforePacks {
            get {
                return ResourceManager.GetString("ERR_NormalTypeParametersComeBeforePacks", resourceCulture);
            }
        }
        
        internal static string ERR_NumberSuffixNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_NumberSuffixNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_NumericLiteralTooLarge {
            get {
                return ResourceManager.GetString("ERR_NumericLiteralTooLarge", resourceCulture);
            }
        }
        
        internal static string ERR_OctalNumericLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_OctalNumericLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_OnlyOneTableTypeIndexerIsAllowed {
            get {
                return ResourceManager.GetString("ERR_OnlyOneTableTypeIndexerIsAllowed", resourceCulture);
            }
        }
        
        internal static string ERR_RbraceExpected {
            get {
                return ResourceManager.GetString("ERR_RbraceExpected", resourceCulture);
            }
        }
        
        internal static string ERR_SemicolonExpected {
            get {
                return ResourceManager.GetString("ERR_SemicolonExpected", resourceCulture);
            }
        }
        
        internal static string ERR_ShebangNotSupportedInLuaVersion {
            get {
                return ResourceManager.GetString("ERR_ShebangNotSupportedInLuaVersion", resourceCulture);
            }
        }
        
        internal static string ERR_SyntaxError {
            get {
                return ResourceManager.GetString("ERR_SyntaxError", resourceCulture);
            }
        }
        
        internal static string ERR_TypedLuaNotSupportedInLuaVersion {
            get {
                return ResourceManager.GetString("ERR_TypedLuaNotSupportedInLuaVersion", resourceCulture);
            }
        }
        
        internal static string ERR_UnderscoreInNumericLiteralNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_UnderscoreInNumericLiteralNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_UnescapedLineBreakInString {
            get {
                return ResourceManager.GetString("ERR_UnescapedLineBreakInString", resourceCulture);
            }
        }
        
        internal static string ERR_UnexpectedToken {
            get {
                return ResourceManager.GetString("ERR_UnexpectedToken", resourceCulture);
            }
        }
        
        internal static string ERR_UnfinishedLongComment {
            get {
                return ResourceManager.GetString("ERR_UnfinishedLongComment", resourceCulture);
            }
        }
        
        internal static string ERR_UnfinishedString {
            get {
                return ResourceManager.GetString("ERR_UnfinishedString", resourceCulture);
            }
        }
        
        internal static string ERR_UnicodeEscapeMissingCloseBrace {
            get {
                return ResourceManager.GetString("ERR_UnicodeEscapeMissingCloseBrace", resourceCulture);
            }
        }
        
        internal static string ERR_UnicodeEscapeMissingOpenBrace {
            get {
                return ResourceManager.GetString("ERR_UnicodeEscapeMissingOpenBrace", resourceCulture);
            }
        }
        
        internal static string ERR_UnicodeEscapesNotSupportedLuaInVersion {
            get {
                return ResourceManager.GetString("ERR_UnicodeEscapesNotSupportedLuaInVersion", resourceCulture);
            }
        }
        
        internal static string ERR_WhitespaceEscapeNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_WhitespaceEscapeNotSupportedInVersion", resourceCulture);
            }
        }
        
        internal static string ThisMethodCanOnlyBeUsedToCreateTokens {
            get {
                return ResourceManager.GetString("ThisMethodCanOnlyBeUsedToCreateTokens", resourceCulture);
            }
        }
        
        internal static string UseIdentifierToCreateIdentifiers {
            get {
                return ResourceManager.GetString("UseIdentifierToCreateIdentifiers", resourceCulture);
            }
        }
        
        internal static string UseLiteralForNumeric {
            get {
                return ResourceManager.GetString("UseLiteralForNumeric", resourceCulture);
            }
        }
        
        internal static string WRN_LineBreakMayAffectErrorReporting {
            get {
                return ResourceManager.GetString("WRN_LineBreakMayAffectErrorReporting", resourceCulture);
            }
        }
        
        internal static string WRN_LineBreakMayAffectErrorReporting_Description {
            get {
                return ResourceManager.GetString("WRN_LineBreakMayAffectErrorReporting_Description", resourceCulture);
            }
        }
        
        internal static string WRN_LineBreakMayAffectErrorReporting_Title {
            get {
                return ResourceManager.GetString("WRN_LineBreakMayAffectErrorReporting_Title", resourceCulture);
            }
        }
        
        internal static string ERR_InterpolatedStringMustStartWithBacktickCharacter {
            get {
                return ResourceManager.GetString("ERR_InterpolatedStringMustStartWithBacktickCharacter", resourceCulture);
            }
        }
        
        internal static string ERR_UnclosedExpressionHole {
            get {
                return ResourceManager.GetString("ERR_UnclosedExpressionHole", resourceCulture);
            }
        }
        
        internal static string ERR_DoubleBraceInInterpolation {
            get {
                return ResourceManager.GetString("ERR_DoubleBraceInInterpolation", resourceCulture);
            }
        }
        
        internal static string ERR_InterpolatedStringsNotSupportedInVersion {
            get {
                return ResourceManager.GetString("ERR_InterpolatedStringsNotSupportedInVersion", resourceCulture);
            }
        }
    }
}
