# .SYNOPSIS
# This script basically runs Loretta.CLI with instrumentation profiling enabled.
# .DESCRIPTION
# The files generated by this type of profiling are VERY LARGE so put the output
# in a disk where you have spare space in.
# .PARAMETER Output
# Literal path to the instrumentation profiling session's output.
# .PARAMETER VSPath
# Literal path to your VS installation.
# .PARAMETER VSPerfToolsPath
# Literal path to your VS installation's perf tools.

param (
	[ValidateNotNullOrEmpty()]
	[string] $Output = "report.vsp",

	[ValidateNotNullOrEmpty()]
	[string] $VSPath = "B:\Program Files\Microsoft Visual Studio 2022 Preview",

	[ValidateNotNullOrEmpty()]
	[string] $VSPerfToolsPath = "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2022"
)

function Pause ($Message = "Press any key to continue...") {
	Write-Host -NoNewLine $Message
	[System.Console]::ReadKey($True)
	Write-Host ""
}

& "$VSPerfToolsPath\x64\VSPerfCmd.exe" /START:TRACE /WAITSTART "/OUTPUT:$Output"
& "$PSScriptRoot\cli-with-profiling.ps1" -VSPath $VSPath
& "$VSPerfToolsPath\x64\VSPerfCmd.exe" /SHUTDOWN