name: Long Running Lexer Tests

on:
  push:
    paths:
      - '**/Parser/Lexer*.cs'
      - '**/Test/Syntax/Lexical/**'
  pull_request:
    paths:
      - '**/Parser/Lexer*.cs'
      - '**/Test/Syntax/Lexical/**'
  workflow_dispatch:

jobs:
  build:
    name: Run Lexer Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            installDir: /usr/share/dotnet
          - os: windows-latest
            installDir: C:\Program Files\dotnet
          - os: macos-latest
            installDir: /Users/runner/.dotnet
    timeout-minutes: 720
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run Full Lexer Tests
        env:
          LORETTA_LONG_LEXER_TESTS: true
        run: dotnet test --configuration Release --no-build