name: Nightly Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build-and-test.yml

  extract-nightly-info:
    name: Extract Nightly Info
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write # Allow to checkout (read) and push tags (write)
    outputs:
      full-version: ${{ steps.gen-version.outputs.VERSION }}
      no-prefix-version: ${{ steps.gen-version.outputs.NO_PREFIX_VERSION }}
      has-nightly: ${{ steps.gen-version.outputs.HAS_NIGHTLY }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Extract Latest Changes
        run: ./build/Extract-LatestChanges.ps1
        shell: pwsh
      - uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 8.0.x
      - name: Generate Version Number
        id: gen-version
        run: |
          dotnet run --project src/Tools/NightlyTool --verbosity quiet -- $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Tag New Nightly
        if: steps.gen-version.outputs.HAS_NIGHTLY == 'yes'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag --annotate --file=LATESTCHANGES.md --cleanup=whitespace ${{ steps.gen-version.outputs.VERSION }}
          git push origin ${{ steps.gen-version.outputs.VERSION }}

  release:
    name: Release
    runs-on: windows-latest
    needs:
      - build
      - extract-nightly-info
    permissions:
      contents: write # Allow to checkout (read) and make new releases (write)
    if: needs.extract-nightly-info.outputs.has-nightly == 'yes'
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Package Libraries
        run: |
          dotnet pack \
            --configuration Release \
            --output ./packages \
            --include-symbols \
            -p:Version=${{ needs.extract-nightly-info.outputs.no-prefix-version }}
        shell: bash
      - name: Get a short-lived NuGet API key
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish Packages to NuGet
        run: |
          dotnet nuget push ./packages/*.nupkg \
            --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        shell: bash
      - name: Extract Latest Changes
        run: ./build/Extract-LatestChanges.ps1
        shell: pwsh
      - name: Create Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: ${{ needs.extract-nightly-info.outputs.full-version }}
          tag_name: ${{ needs.extract-nightly-info.outputs.full-version }}
          body_path: LATESTCHANGES.md
          prerelease: true
