name: Stable Release

on:
  push:
    tags:
      - 'v*'
      - '!v*-nightly.*'

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml

  release:
    name: Release
    runs-on: windows-latest
    needs: [build]
    permissions:
      contents: write # Allow checkout (read) and release creation (write)
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Generate NuGet packages
        run: dotnet pack --configuration Release --output ./packages --no-restore --include-symbols -p:SymbolPackageFormat=snupkg
      - name: Publish packages
        run: |
          Get-ChildItem -Path ./packages/ -Filter *.nupkg -File -Name | ForEach-Object {
            dotnet nuget push ./packages/$_ --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          }
        shell: pwsh

      - name: Extract Latest Changes
        run: ./build/Extract-LatestChanges.ps1
        shell: pwsh
      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: LATESTCHANGES.md
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
